before:
  hooks:
    - go mod download
builds:
  - <<: &build_defaults
      binary: go-starz
      ldflags:
        - -s -w -X github.com/sachaos/go-starz/cmd.version={{.Version}}
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64]
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: sachaos
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/sachaos/go-starz
    description: Show GitHub stars
    skip_upload: auto
    test: |
      system "#{bin}/go-starz", "--version"
